package com.poc.consumer.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * JPA entity representing a message that has been received from the Apache
 * Pulsar
 * topic and persisted in the H2 in-memory database.
 *
 * <p>
 * The table name is {@code messages}. Each row corresponds to exactly one
 * Pulsar message consumed by
 * {@link com.poc.consumer.service.PulsarConsumerListener}.
 * The {@code messageId} column holds the UUID generated by the producer and is
 * used to enforce idempotency — if the same message is delivered more than once
 * (Pulsar at-least-once delivery), the duplicate will be dropped.
 * </p>
 *
 * <p>
 * Because H2 is configured with {@code ddl-auto: create-drop}, this schema
 * is recreated on every application start and is lost on shutdown.
 * </p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "messages")
public class Message {

    /**
     * Auto-generated surrogate primary key assigned by H2's identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * UUID propagated from the producer's {@code MessageEvent.messageId}.
     * Declared {@code unique} to prevent duplicate rows for the same Pulsar
     * message.
     */
    @Column(nullable = false, unique = true)
    private String messageId;

    /**
     * The message body received from the Pulsar topic.
     * Supports up to 2,000 characters.
     */
    @Column(nullable = false, length = 2000)
    private String content;

    /**
     * The originator identifier forwarded from the producer. May be {@code null}.
     */
    private String sender;

    /** Timestamp at which the producer created and published the event. */
    private LocalDateTime producedAt;

    /** Timestamp at which this consumer received and persisted the event. */
    @Column(nullable = false)
    private LocalDateTime receivedAt;
}
