package com.poc.consumer.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Data Transfer Object (DTO) that mirrors the event schema published by the
 * {@code pulsar-producer} microservice.
 *
 * <p>
 * When the {@link com.poc.consumer.service.PulsarConsumerListener} receives
 * a raw JSON byte array from Pulsar, it deserializes it into this class using
 * Jackson's {@code ObjectMapper}. The schema must remain in sync with the
 * producer's {@code MessageEvent}.
 * </p>
 *
 * <p>
 * <b>Example JSON consumed from Pulsar topic:</b>
 * </p>
 * 
 * <pre>{@code
 * {
 *   "messageId": "550e8400-e29b-41d4-a716-446655440000",
 *   "content":   "Hello Pulsar!",
 *   "sender":    "TestClient",
 *   "timestamp": "2026-03-03T12:02:00"
 * }
 * }</pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MessageEvent {

    /**
     * UUID generated by the producer, used for deduplication.
     * The consumer checks this against
     * {@code MessageRepository.existsByMessageId()}
     * before persisting.
     */
    private String messageId;

    /**
     * The message body as provided by the original HTTP request to the producer.
     */
    private String content;

    /** The sender identifier forwarded from the producer's HTTP request. */
    private String sender;

    /** Timestamp set by the producer at the moment of publishing. */
    private LocalDateTime timestamp;
}
