package com.poc.producer.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents the event payload that is serialized to JSON and published
 * to the Apache Pulsar topic.
 *
 * <p>
 * This event is produced by
 * {@link com.poc.producer.service.MessageProducerService}
 * and consumed (and deserialized) by the {@code pulsar-consumer} microservice.
 * Both sides must agree on this schema; any field changes are therefore
 * a breaking change for the consumer.
 * </p>
 *
 * <p>
 * <b>Example serialized form:</b>
 * </p>
 * 
 * <pre>{@code
 * {
 *   "messageId": "550e8400-e29b-41d4-a716-446655440000",
 *   "content":   "Hello Pulsar!",
 *   "sender":    "TestClient",
 *   "timestamp": "2026-03-03T12:02:00"
 * }
 * }</pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MessageEvent {

    /**
     * Universally unique identifier for this event, generated by the producer.
     * Used by the consumer for idempotency / deduplication checks.
     */
    private String messageId;

    /** The message body forwarded from the original {@link MessageRequest}. */
    private String content;

    /** The originator of the message, forwarded from {@link MessageRequest}. */
    private String sender;

    /** Wall-clock timestamp at which the producer created this event. */
    private LocalDateTime timestamp;
}
