package com.poc.consumer.repository;

import com.poc.consumer.entity.Message;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for {@link Message} entities.
 *
 * <p>
 * Provides standard CRUD operations inherited from {@link JpaRepository},
 * plus a custom query method for deduplication.
 * </p>
 *
 * <p>
 * The underlying store is an H2 in-memory database configured in
 * {@code application.yml} ({@code spring.datasource.url=jdbc:h2:mem:orderdb}).
 * All data is lost when the application shuts down.
 * </p>
 */
@Repository
public interface MessageRepository extends JpaRepository<Message, Long> {

    /**
     * Checks whether a message with the given producer-assigned UUID already
     * exists in the database.
     *
     * <p>
     * Used by {@link com.poc.consumer.service.PulsarConsumerListener} to
     * implement idempotent consumption: if Pulsar re-delivers a message
     * (at-least-once
     * semantics), this check prevents inserting a duplicate row.
     * </p>
     *
     * @param messageId the UUID generated by the producer
     * @return {@code true} if a message with this ID has already been saved
     */
    boolean existsByMessageId(String messageId);
}
